### ISSUE TITLE
__cxa_pure_virtual defined twice

### ISSUE THREAD

**Issue by rei-vilo** [Seeed-Studio/Seeed_Arduino_rpcUnified#1]
`__cxa_pure_virtual` seems to be defined twice, resulting in an error

> /Arduino/Libraries/Seeed_Arduino_rpcUnified/src/erpc/erpc_port_freertos.cpp:74: Multiple definition of `__cxa_pure_virtual'

Indeed, `__cxa_pure_virtual` appears twice: 

1. `~/Arduino/Libraries/Seeed_Arduino_rpcUnified/src/erpc/erpc_port_freertos.cpp`
2. `~/Library/Arduino15/packages/Seeeduino/hardware/samd/1.8.0/cores/arduino/abi.cpp`

As a quick and dirty turn-around, I've commented `__cxa_pure_virtual` in `abi.cpp`, but I haven't check whether other libraries might be impacted.

What could be a cleaner solution? Thank you!

**Comment by rei-vilo** [comment]
Changing 

https://github.com/Seeed-Studio/Seeed_Arduino_rpcUnified/blob/9b30c8a216cb312b8ad8c3e1dc1e4187e4f084ea/src/erpc/erpc_port_freertos.cpp#L73-L77

for

```
extern "C" void __cxa_pure_virtual(void) __attribute__ ((weak));

extern "C" void __cxa_pure_virtual()
{
    while (1)
        ;
}
```

solves the issue.

**Comment by LynnL4** [comment]
Thanks! @rei-vilo [53302c9e59bcf81940ea49dcaa77841260fcb81f](https://github.com/Seeed-Studio/Seeed_Arduino_rpcUnified/commit/53302c9e59bcf81940ea49dcaa77841260fcb81f)
