### ISSUE TITLE
Secure server connection attempt hangs on v2.1.1

### ISSUE THREAD

**Issue by LordParsley** [Seeed-Studio/Seeed_Arduino_rpcUnified#12]
**Describe the bug**

In the tutorial, [Accessing to GitHub using Wio Terminal](https://wiki.seeedstudio.com/Wio-Terminal-Reading-Github/), a secure connection is made to https://api.github.com/repos/micropython/micropython using a CA certificate & `WiFiClientSecure`.

Instead of connecting to the server, the example programme hangs on:

```
17:06:39.841 -> Starting connection to server...
```

**To Reproduce**

Steps to reproduce the behaviour:
1. Set up the Wio Terminal's networking based on https://wiki.seeedstudio.com/Wio-Terminal-Network-Overview/.
2. In the above, use the latest release of `Seeed_Arduino_rpcUnified` (`v2.1.1`).
3. Run the demo programme.
4. The Wio output remains on "Connecting to Server.." forever.

Bisecting previous versions, this behaviour seems to have started on commit `98cd4a07` which was merged into `v2.1.0`.

❌ commit `f8935b82` : `v2.1.1`
❌ commit `c0be4e91` : `v2.1.0`
❌ ... commit `98cd4a07` : reduce delay
✅ commit `ad514c73` : add null pointer check in pbuf erpc functions
✅ commit `4fd46b11` : `v2.0.2`

**Expected behaviour**

A successful connection to Github should be followed by parsing the JSON response & displaying the number of stars, etc. on the repo.

The tutorial runs as expected when using `Seeed_Arduino_rpcUnified` `v2.0.2` & the last commit `ad514c73` before merging in "reduce delay" related work.

**Additional context**

I'm not really sure how to see debug output for RPC (or really how it works), but since the normal behaviour of `WifiSecureClient` is to time out – & it never does – it seems like the underlying client is never getting the message intended for it (or else the RPC response is not returned?).

**Comment by Pillar1989** [comment]
@lakshanthad  @matsujirushi  We need to confirm as soon as possible whether this is a problem with the RTL SDK or with our communication protocol itself. Preferably it is a problem with the RTL SDK and I can contact the RTL FAE to resolve the issue.

**Comment by Pillar1989** [comment]
https://github.com/Seeed-Studio/Seeed_Arduino_mbedtls/issues/4

**Comment by lakshanthad** [comment]
Hi @LordParsley,

I have tested the following tutorial with `rpcUnified v2.1.1` and worked perfectly:
https://wiki.seeedstudio.com/Wio-Terminal-Reading-Github/

Make sure to update your RTL firmware as well. Currently the RTL firmware is at `v2.1.0`

Please follow the wiki below to burn the latest RTL firmware:
https://wiki.seeedstudio.com/Wio-Terminal-Network-Overview/

Please let me know the result 

Best Regards,
Lakshantha

**Comment by LordParsley** [comment]
Thanks very much @lakshanthad ! Appreciated. I see I was on `20201201-seeed-ambd-firmware-rpc-v2.0.3`. I'll upgrade, retest & confirm.

**Comment by LordParsley** [comment]
Thanks @lakshanthad – working 100% on `v2.1.1` with the latest firmware `20201228-seeed-ambd-firmware-rpc-v2.1.0`.

Sorry I missed that f/w update & thanks for the guidance! I've subscribed to releases now 😉
