### ISSUE TITLE
Please publish library in PlatformIO library registery

### ISSUE THREAD

**Issue by maxgerhardt** [Seeed-Studio/Seeed_Arduino_rpcUnified#15]
**Is your feature request related to a problem? Please describe.**
This library cannot be found in the PlatformIO library registry.

**Describe the solution you'd like**

Per https://community.platformio.org/t/arduino-libraries-missing-from-library-manager/20131 a PlatformIO has discovered that most of the Seeed-Studio libraries that he wants to use are already uploaded to the [PlatformIO library registry](https://platformio.org/lib), but the library in this repository is not. 

Can you please publish it as you did with the other libraries using the `seeed-studio` account? :)

**Comment by Pillar1989** [comment]
@lakshanthad  Please handle these issues.

**Comment by lakshanthad** [comment]
Hi @maxgerhardt,

It seems that platformIO syncs all the libraries which are included in the **Arduino Library Manager**. **Seeed_Arduino_rpcUnified** is already included in the Arduino Library Manager, but however, there is an issue in the "email" section of the library.properties file. This seems to be the reason why platformIO didn't sync this library.

https://community.platformio.org/t/arduino-libraries-missing-from-library-manager/20131/7
According to the above PR, I have created a new release now.

https://github.com/Seeed-Studio/Seeed_Arduino_rpcUnified/releases/tag/v2.1.3

Please wait a couple of hours until it gets automatically added to platformIO Library Manager.

Best Regards,
Lakshantha

**Comment by lakshanthad** [comment]
https://platformio.org/lib/show/11971/Seeed%20Arduino%20rpcUnified

It's available now

**Comment by maxgerhardt** [comment]
Indeed, thanks.
