### ISSUE TITLE
v2.1.2 does not respond on Wio Terminal

### ISSUE THREAD

**Issue by baldengineer** [Seeed-Studio/Seeed_Arduino_rpcUnified#17]
**Describe the bug**
If using version 2.1.2 of rpcUnified, at least two WiFi examples do not work.
Using the version check code in the Wio Terminal's "[Network Overview](https://wiki.seeedstudio.com/Wio-Terminal-Network-Overview/#check-rtl8720-firmware-version-from-arduino-ide)" tutorial, the Serial monitor never prints anything. I modified the code to print a message before and after the call to `rpc_system_version()`. After that call is made, the Wio never responds.

The `WiFiScan` example in the `rpcWiFi` library also does not work with version 2.1.2.

**To Reproduce**
1. Install version 2.1.2 from the Arduino library manager
2. Run the code listed in the [Wio Terminal Network Overview](https://wiki.seeedstudio.com/Wio-Terminal-Network-Overview/#check-rtl8720-firmware-version-from-arduino-ide) page.

**Expected behavior**
A string returning the firmware version

**Desktop (please complete the following information):**
- Windows 10
- Arduino IDE 1.8.13
- Seeed Arduino rpcWiFi 1.0.3
- Seeed SAMD Boards 1.8.1

**Additional context**
I downgraded the firmware on the Wio to 2.1.1 as well. Not sure if that was necessary or not.

**Comment by Pillar1989** [comment]
@baldengineer  I think you need to update Seeed Arduino rpcWiFi 1.0.3 to   1.0.4, There is a strong binding between the versions.
