### ISSUE TITLE
lwip_select() does not update fd_set arguments

### ISSUE THREAD

**Issue by t-ikegami** [Seeed-Studio/Seeed_Arduino_rpcUnified#18]
**Describe the bug**
Usually, select system call will update the passed fd_sets on return, such that bits correspoinding to active fds are on.  However, the present eRPC definition of rpc_lwip_select() returns only the result code, and fd_sets (readset/writeset/exceptset) are not kicked-back from RTL8720.  I'm not much confident, but IDL should be:

`rpc_lwip_select(int32 maxfdp1, in binary readset @nullable, in binary writeset @nullable, in binary exceptset @nullable, in binary timeout @nullable) -> int32`
↓
`rpc_lwip_select(int32 maxfdp1, inout binary readset @nullable, inout binary writeset @nullable, inout binary exceptset @nullable, in binary timeout @nullable) -> int32`

**Comment by Pillar1989** [comment]
Feel free to send us a PR and we would like to see your signature inside the code. @t-ikegami

**Comment by t-ikegami** [comment]
I'm afraid that the fix is not localized to this repository, but should be in sync with RTL8720 firmware, `https://github.com/Seeed-Studio/seeed-ambd-firmware`
