### ISSUE TITLE
SERCOM.h: No such file or directory

### ISSUE THREAD

**Issue by mcavalcante** [Seeed-Studio/Seeed_Arduino_rpcUnified#19]
**Describe the bug**
I´ve copy this script exactly as it is to my Arduino IDE, but when a try to upload it to my RTL8720DN, I get a message stating it is missing the library SERCOM.h. I tried all ways to install this library, no progress.

**To Reproduce**
Just try to compile or to upload this script exactly as it is to the module RTL8720DN through Arduino IDE.

**Expected behavior**
No compilation error nor any issue to upload the sketch to RTL8720DN.

**Screenshots**
Picture attached:
![sercom_error_rtl8720dn](https://user-images.githubusercontent.com/14970127/123463368-d098a080-d5c1-11eb-8eb0-a311edfeb1c9.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Arduino IDE: 1.8.15
 - Realtek Ameba Boards library: 3.0.9-build20210520

**Smartphone (please complete the following information):**
not applicable

**Additional context**
I´m trying to port some ESP32 codes to RTL8720, but I´m finding difficulties to this. The samples I´m need now are: WPS and SSDP, both of them avaible in Arduino IDE examples for ESP32, but not for RTL8720DN.

**Comment by Pillar1989** [comment]
@mcavalcante  sorry, we don't have any experience with ESP32
