### ISSUE TITLE
.erpc available?

### ISSUE THREAD

**Issue by stonehippo** [Seeed-Studio/Seeed_Arduino_rpcUnified#21]
I'm working on getting Wio Terminal eRPC working with CircuitPython, and I can see that `erpcgen` was used to generate the interface files in `src/erpc`. However, I don't see a `.erpc` file in the repo. Is it possible to include that here? I'd like to start by generating a set of client-side Python interface files and I'd rather use the canonical IDL (though I could also write my own based on the API here).

**Comment by Pillar1989** [comment]
https://github.com/Seeed-Studio/seeed-ambd-firmware/tree/master/erpc_idl @stonehippo  That's all `*.erpc` files.

**Comment by stonehippo** [comment]
@Pillar1989 Thanks! That was the repo I _didn't_ look in. ;-)
