### ISSUE TITLE
Typo in file Seeed_Arduino_rpcUnified/library.properties

### ISSUE THREAD

**Issue by RoSchmi** [Seeed-Studio/Seeed_Arduino_rpcUnified#5]
![Typo in Seeed_Arduino_rpcUnified_library properties](https://user-images.githubusercontent.com/24595510/98834844-f8c2fd00-243f-11eb-9cfe-7bb1a3d2bca0.png)

'Seeed_Arduino_rpcUnified' is written wrong as 'Seeed_Arduino_rpcUnifed'

I'm not sure if this can the reason for not found references

**Comment by LynnL4** [comment]
Thanks,  https://github.com/Seeed-Studio/Seeed_Arduino_rpcUnified/commit/25c7573e7ac9d96d39abbc40ca8dcccead49ad54
