### ISSUE TITLE
Too slow get_ssl_receive()

### ISSUE THREAD

**Issue by matsujirushi** [Seeed-Studio/Seeed_Arduino_rpcUnified#7]
get_ssl_receive() takes 50milliseconds.

![image](https://user-images.githubusercontent.com/8079404/102733176-ecf02200-437f-11eb-8f18-eba53821f5b9.png)
![image](https://user-images.githubusercontent.com/8079404/102733227-0beeb400-4380-11eb-9d32-e0a724ba5b70.png)

This issue to lower application performance because this function is called from WiFiClientSecure::available() repeatly.
Could you be faster?

**Comment by matsujirushi** [comment]
I changed this library and RTL firmware.
Please check and will merge.

**Timing:**
![image](https://user-images.githubusercontent.com/8079404/102876743-ff09b780-4488-11eb-978d-2cd9e1787c21.png)


**Modified code:**
https://github.com/matsujirushi/Seeed_Arduino_rpcUnified/tree/matsujirushi-patch2
https://github.com/matsujirushi/seeed-ambd-firmware/tree/matsujirushi-patch2

**Comment by Pillar1989** [comment]
@matsujirushi  Thank you so much.

**Comment by Pillar1989** [comment]
@matsujirushi  Do you think it is necessary to include RTL FW version checking at the beginning of the code?

**Comment by matsujirushi** [comment]
Hi @Pillar1989 ,
Yes. Developer friendly :-)

**Comment by matsujirushi** [comment]
FYI
Next idea for performance up.
https://twitter.com/matsujirushi12/status/1341359957619314689

**Comment by matsujirushi** [comment]
More updated.

**Timing:**
![image](https://user-images.githubusercontent.com/8079404/102950961-19867400-450f-11eb-8334-d76dff22888d.png)

**Modified code:**
https://github.com/matsujirushi/Seeed_Arduino_rpcUnified/tree/matsujirushi-patch3
https://github.com/matsujirushi/seeed-ambd-firmware/tree/matsujirushi-patch3

**Comment by Pillar1989** [comment]
@matsujirushi  Can this issue be closed?

**Comment by matsujirushi** [comment]
Hi @Pillar1989 ,
Yes, if you are merged the patch3.
